### ISSUE TITLE
Screenshot script won't run on Windows under Node 12

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockSite#107]
The whole thing is just a hot mess

Error: Cannot find module 'C:\Users\yami\Documents\GitHub\SockSite\node_module
s\sqlite3\lib\binding\node-v14-win32-x64\node_sqlite3.node'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at Object.<anonymous> (C:\Users\yami\Documents\GitHub\SockSite\node_module (edited)

yamikuronue [11:51 AM]
C:\Users\yami\Documents\GitHub\SockSite>npm install sqlite
npm WARN excluding symbolic link sqlite3_bindings.node -> build/default/sqlite3_
bindings.node

> sqlite@1.0.4 preinstall C:\Users\yami\Documents\GitHub\SockSite\node_modules
> \sqlite
> node-waf configure build

**Comment by AccaliaDeElementia** [comment]
looks like an issue with sqlite3 actually.

i got the same thing when trying on linux where it failed utterly if i didn't have g++ installed.

that's something i'll have to sort out for v2.0 i see

maybe sqlite is just not that node friendly?
